#[openstack:vars]
#ansible_user=rocky
[all:vars]
ansible_user=root
ansible_ssh_pass=soldesk
# 호스트 키 체크를 끄면 처음 접속 시 yes/no를 묻지 않아 편리합니다.
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[controllers]
controller ansible_host=192.168.0.146 mgmt_ip=192.168.0.146

[computes]
compute1 ansible_host=192.168.0.150 mgmt_ip=192.168.0.150

[openstack:children]
controllers
computes